# Basic Information
title: "Qian Li"
position: "Undergraduate Researcher"
affiliation: "Jiangnan University"
email: "1043230208 (at) stu.jiangnan.edu.cn"

# Search Engine Optimization
keywords: "Qian Li, Embodied Intelligence, Robot Learning, Robotic Manipulation, Vision-Language-Action Models"
description: "Qian Li is an undergraduate researcher at Jiangnan University, focusing on embodied intelligence, robot learning, and robotic manipulation."
canonical: "https://qianli-1118.github.io/"

# Links
cv_link: "./assets/files/个人简历.pdf"
github_link: "https://github.com/qianli-1118/"

# Images
avatar: "./assets/img/蓝底证件照.jpg"
favicon: "./assets/img/favicon.png"
favicon_dark: "./assets/img/favicon-dark.png"

# Display Settings
enable_footnote: true
auto_dark_mode: true
font: "Sans Serif"

# Minimal Light Theme
remote_theme: yaoyao-liu/minimal-light

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
